// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $breakfasts from "./routes/breakfasts.tsx";
import * as $cart from "./routes/cart.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $luncheons from "./routes/luncheons.tsx";
import * as $product_product_ from "./routes/product/[product].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $buttonadd from "./islands/buttonadd.tsx";
import * as $num from "./islands/num.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/breakfasts.tsx": $breakfasts,
    "./routes/cart.tsx": $cart,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/luncheons.tsx": $luncheons,
    "./routes/product/[product].tsx": $product_product_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/buttonadd.tsx": $buttonadd,
    "./islands/num.tsx": $num,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
